name: cloud-storage-uploader Integration
on: [push]
jobs:
  gcloud:
    name: with setup-gcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-gcloud
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: make temp folder and file
        run: |
          mkdir -p test
          touch test/test1.txt
      - id: upload
        name: upload file
        uses: ./cloud-storage-uploader
        with:
          path: ./test/test2.txt
          destination: ${{ secrets.TEST_BUCKET_NAME }}/testprefix
      - name: get output
        run: echo '${{ steps.upload.outputs.uploaded }}'

  b64_json:
    name: with base64 json creds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make temp folder and files
        run: |
          mkdir -p test
          touch test/test1.txt
          touch test/test2.txt
      - id: upload
        name: upload folder
        uses: ./cloud-storage-uploader
        with:
          path: ./test
          destination: bucket/testprefix
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: get output
        run: echo '${{ steps.upload.outputs.uploaded }}'

  json:
    name: with json creds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make temp folder and files
        run: |
          mkdir -p test
          touch test/test1.txt
          touch test/test2.txt
      - id: upload
        name: upload folder
        uses: ./cloud-storage-uploader
        with:
          path: ./test
          destination: bucket/testprefix
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
      - name: get output
        run: echo '${{ steps.upload.outputs.uploaded }}'

  mocha-it:
    name: mocha integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-gcloud
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: npm install
        run: npm install
        working-directory: ./cloud-storage-uploader

      - name: npm lint
        run: npm run lint
        working-directory: ./cloud-storage-uploader

      - name: npm test
        run: npm run test
        working-directory: ./cloud-storage-uploader
        env:
          TEST_BUCKET: ${{ secrets.TEST_BUCKET_NAME }}
